#! /bin/bash

echo " [Verres] - Attempting to build docker environment"

if [ "$(make build)" -ne 0 ]
then
  echo " [Verres] - ERROR: Couldn't build environment..."
  exit 1
fi

source environment_setup.sh

# shellcheck disable=SC2124
docker run -it --rm --network host \
  --name verres_environment \
  -v $(realpath ${VERRES_ARTIFACTORY}):/artifactory \
  -v $(realpath ${VERRES_MODELS}):/models \
  -v $(realpath ${VERRES_DATA}):/data \
  -v $(pwd):/workspace \
  -u $(id -u) \
  -e DISPLAY \
  -v /tmp/.X11-unix/:/tmp/.X11-unix \
  -v /home/${USER}/.Xauthority:/home/${USER}/.Xauthority \
  verres/environment:latest \
  python main.py --config $@
