dependencies:
  - python~=3.9
  - jupyter
  - matplotlib
  - numpy
  - pillow
  - pip
  - pydantic
  - scipy
  - tensorboard
  - tensorflow-mkl
  - tqdm
  - pip:
    - git+https://github.com/csxeba/Artifactorium.git
    - Cython
    - opencv-python
    - pycocotools-fix
    - pydot-ng
    - pyyaml
    - gast<0.4
