dependencies:
  - jupyter
  - matplotlib
  - numpy
  - pillow
  - pip
  - scipy
  - tensorboard
  - tensorflow-gpu
  - tqdm
  - yaml
  - pip:
    - git+https://github.com/csxeba/Artifactorium.git
    - opencv-python
    - pycocotools-fix
    - pydot-ng
