context:
  experiment_set: od
  experiment_name: baseline
  artifactory_root: /data/My Drive/artifactory
  execution_type: training
  verbose: 2

model:
  input_width: 320
  input_height: 200
  maximum_stride: 8
  backbone_spec:
    name: ResNet50
    feature_layers:
      - conv2_block3_out  # stride: 4 width: 256
      - conv3_block4_out  # stride: 8 width: 512
#      - conv4_block6_out  # stride: 16 width: 1024
#      - conv5_block3_out  # stride: 32 width: 2048
  neck_spec:
    name: AutoFusion
    output_stride: 4
    output_width: 64
  head_spec:
    name: od

training:
  data:
    - name: cocodoom
      root: /data/Datasets/cocodoom
      subset: train
      sampling_probability: 1.0
      transformations:
        - { name: image, stride: 1 }
        - { name: uniform_heatmap, stride: 4 }
        - { name: refinement, stride: 4 }
        - { name: box_wh, stride: 4 }
      kwargs:
        full: False
        split: run
  epochs: 120
  steps_per_epoch: 1000
  batch_size: 8
  criteria_spec:
    losses:
      - name: focal
        feature: heatmap
        weight: 1.
      - name: sae
        feature: refinement
        weight: 10.
        sparse: True
      - name: sae
        feature: box_wh
        weight: 1.
        sparse: True
  optimizer_spec:
    name: Adam
  lr_schedule_spec:
    name: PiecewiseConstantDecay
    boundaries: [20000, 40000]
    values: [0.1, 0.01, 0.001]
  callbacks:
    - { name: LatestModelCheckpoint }
#    - { name: ObjectMAP, checkpoint_best: True }
    - { name: CSVLogger }
    - { name: TensorBoard }

evaluation:
  data:
    - name: cocodoom
      root: /data/Datasets/cocodoom
      subset: val
      transformations:
        - { name: image, stride: 1 }
      kwargs:
        full: False
        split: run
  detection_output_file : default

inference:
  data:
    - name: cocodoom
      root: /data/Datasets/cocodoom
      subset: val
      transformations:
        - { name: image, stride: 1 }
      kwargs:
        full: True
        split: run

  visualization_mode: detection
  to_screen: True
  output_video_path: None
  fps: 25
  total_num_frames: 200
